url: "https://felixleitner.com"
title: "Felix Leitner"

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

collections_dir: _collections

collections:
  skills:
    output: false

esbuild:
  bundle: true
  minify: environment
  sourcemap: environment
  files:
    - /assets/js/main.js
